api:
  insecure: false
  dashboard: true
  debug: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  # comentar esta sección si no se quiere SSL en local
  https:
    address: ":443"

providers:
  # Enable Docker Provider.
  docker:
    endpoint: "unix:///var/run/docker.sock" # Daemon Docker
  # Enable Rancher Provider.
  # rancher:
  #   exposedByDefault: false
  #   defaultRule: "Host(`{{ .Name }}.{{ index .Labels \"customLabel\"}}`)"
  #   enableServiceHealthFilter: false
  #   refreshSeconds: 30
  #   intervalPoll: true
  #   prefix: "/test"

  file:
    filename: /config.yml

# # comentar esta sección si no se quiere SSL en local
certificatesResolvers:
  letsencrypt:
    acme:
      email: "contacto@mywebsite.com"
      storage: /acme.json
      httpChallenge:
        entrypoint: http

# metrics:
#   prometheus:
#     addEntryPointsLabels: true
#     addServicesLabels: true
#     entryPoint: web

# tracing:
# datadog: {}

#
log:
  filePath: "/traefik.log"
  level: ERROR
  format: json

accessLog:
  filePath: "/access.log"
  bufferingSize: 100
  filters:
    statusCodes:
      - "200"
      - "300-302"
    retryAttempts: true
    minDuration: "10ms"
